package astra.mods;

import java.util.List;

/** Galaxy Client module catalog. Implementations are enabled progressively as renderer hooks are wired. */
public final class ModCatalog {
    public record Mod(String id, String name, String category, boolean enabled) {}
    public static final List<Mod> ALL = List.of(
        new Mod("fps-boost","FPS Boost","performance",true),
        new Mod("entity-culling","Entity Culling","performance",true),
        new Mod("particle-optimizer","Particle Optimizer","performance",true),
        new Mod("dynamic-fps","Dynamic FPS","performance",true),
        new Mod("fast-math","Fast Math","performance",true),
        new Mod("chunk-culling","Chunk Culling","performance",true),
        new Mod("render-distance","Render Distance","performance",true),
        new Mod("smart-animations","Smart Animations","performance",true),
        new Mod("lazy-chunk-loading","Lazy Chunk Loading","performance",true),
        new Mod("fast-world-load","Fast World Load","performance",true),
        new Mod("memory-optimizer","Memory Optimizer","performance",true),
        new Mod("texture-cache","Texture Cache","performance",true),
        new Mod("model-cache","Model Cache","performance",true),
        new Mod("shader-cache","Shader Cache","performance",true),
        new Mod("font-cache","Font Cache","performance",true),
        new Mod("light-cache","Light Cache","performance",true),
        new Mod("occlusion-culling","Occlusion Culling","performance",true),
        new Mod("frustum-culling","Frustum Culling","performance",true),
        new Mod("block-culling","Block Culling","performance",true),
        new Mod("mob-culling","Mob Culling","performance",true),
        new Mod("item-entity-culling","Item Entity Culling","performance",true),
        new Mod("sign-culling","Sign Culling","performance",true),
        new Mod("cloud-culling","Cloud Culling","performance",true),
        new Mod("weather-optimizer","Weather Optimizer","performance",true),
        new Mod("sky-optimizer","Sky Optimizer","performance",true),
        new Mod("fog-optimizer","Fog Optimizer","performance",true),
        new Mod("biome-cache","Biome Cache","performance",true),
        new Mod("chunk-mesh-cache","Chunk Mesh Cache","performance",true),
        new Mod("world-renderer","World Renderer","performance",true),
        new Mod("render-batching","Render Batching","performance",true),
        new Mod("texture-animation-control","Texture Animation Control","performance",true),
        new Mod("particle-limit","Particle Limit","performance",true),
        new Mod("entity-tick-optimizer","Entity Tick Optimizer","performance",true),
        new Mod("block-entity-optimizer","Block Entity Optimizer","performance",true),
        new Mod("redstone-optimizer","Redstone Optimizer","performance",true),
        new Mod("pathfinding-optimizer","Pathfinding Optimizer","performance",true),
        new Mod("ai-tick-optimizer","AI Tick Optimizer","performance",true),
        new Mod("random-tick-optimizer","Random Tick Optimizer","performance",true),
        new Mod("sound-optimizer","Sound Optimizer","performance",true),
        new Mod("network-optimizer","Network Optimizer","performance",true),
        new Mod("packet-compression","Packet Compression","performance",true),
        new Mod("connection-stabilizer","Connection Stabilizer","performance",true),
        new Mod("ping-display","Ping Display","utility",true),
        new Mod("fps-display","FPS Display","utility",true),
        new Mod("cps-display","CPS Display","utility",true),
        new Mod("keystrokes","Keystrokes","utility",true),
        new Mod("armor-hud","Armor HUD","utility",true),
        new Mod("potion-hud","Potion HUD","utility",true),
        new Mod("coordinates","Coordinates","utility",true),
        new Mod("clock","Clock","utility",true),
        new Mod("session-time","Session Time","utility",true),
        new Mod("memory-hud","Memory HUD","utility",true),
        new Mod("server-info","Server Info","utility",true),
        new Mod("biome-display","Biome Display","utility",true),
        new Mod("direction-hud","Direction HUD","utility",true),
        new Mod("reach-display","Reach Display","utility",true),
        new Mod("durability-hud","Durability HUD","utility",true),
        new Mod("item-counter","Item Counter","utility",true),
        new Mod("crosshair","Crosshair","visual",true),
        new Mod("hit-color","Hit Color","visual",true),
        new Mod("damage-indicator","Damage Indicator","visual",true),
        new Mod("block-overlay","Block Overlay","visual",true),
        new Mod("motion-blur","Motion Blur","visual",true),
        new Mod("fullbright","Fullbright","visual",true),
        new Mod("clear-water","Clear Water","visual",true),
        new Mod("low-fire","Low Fire","visual",true),
        new Mod("no-pumpkin-overlay","No Pumpkin Overlay","visual",true),
        new Mod("minimal-particles","Minimal Particles","visual",true),
        new Mod("minimal-hud","Minimal HUD","visual",true),
        new Mod("clean-scoreboard","Clean Scoreboard","visual",true),
        new Mod("chat-timestamps","Chat Timestamps","utility",true),
        new Mod("chat-filter","Chat Filter","utility",true),
        new Mod("compact-chat","Compact Chat","utility",true),
        new Mod("chat-background","Chat Background","visual",true),
        new Mod("screenshot-helper","Screenshot Helper","utility",true),
        new Mod("zoom","Zoom","utility",true),
        new Mod("perspective","Perspective","utility",true),
        new Mod("toggle-sprint","Toggle Sprint","utility",true),
        new Mod("toggle-sneak","Toggle Sneak","utility",true),
        new Mod("auto-reconnect","Auto Reconnect","utility",true),
        new Mod("server-selector","Server Selector","utility",true),
        new Mod("quick-play","Quick Play","utility",true),
        new Mod("favorite-servers","Favorite Servers","utility",true),
        new Mod("mod-profiles","Mod Profiles","utility",true),
        new Mod("keybind-manager","Keybind Manager","utility",true),
        new Mod("config-manager","Config Manager","utility",true),
        new Mod("notifications","Notifications","visual",true),
        new Mod("fps-graph","FPS Graph","utility",true),
        new Mod("performance-graph","Performance Graph","utility",true),
        new Mod("lag-meter","Lag Meter","utility",true),
        new Mod("world-time","World Time","utility",true),
        new Mod("compact-inventory","Compact Inventory","visual",true),
        new Mod("inventory-search","Inventory Search","utility",true),
        new Mod("item-preview","Item Preview","visual",true),
        new Mod("tooltips","Tooltips","visual",true),
        new Mod("name-tags","Name Tags","visual",true),
        new Mod("entity-info","Entity Info","utility",true),
        new Mod("chunk-borders","Chunk Borders","visual",true),
        new Mod("grid-overlay","Grid Overlay","visual",true),
        new Mod("debug-panel","Debug Panel","utility",true)
    );
    private ModCatalog() {}
}
